version: '3.9'

services:

  database:
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c123
      MYSQL_DATABASE: u65042380112
      MYSQL_USER: captun
      MYSQL_PASSWORD: c123
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3307:3306
    volumes:
      - ./u65042380112.sql:/docker-entrypoint-initdb.d/u65042380112.sql
    # restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mynetwork
  backend:
    build: ./backend/
    ports:
      - 5000:5000
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: captun
      DB_PASSWORD: c123
      DB_DATABASE: u65042380112
    networks:
      - mynetwork
  frontend:
    build: ./frontend/
    ports:
      - 6542:3000
    environment:
      - http://localhost:5000
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge